apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-api
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
       labels:
         app: {{ template "fullname" . }}
         chart: {{ .Chart.Name }}-{{ .Chart.Version }}
         heritage: {{ .Release.Service }}
         release: {{ .Release.Name }}
         role: fn-api
    spec:
      {{- if .Values.fnserver.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.fnserver.nodeSelector | indent 8 }}
{{- end }}
      {{- if .Values.fnserver.tolerations }}
      tolerations:
{{ toYaml .Values.fnserver.tolerations | indent 8 }}
{{- end }}
      containers:
        - name: fn-api
          image: {{ .Values.fnserver.image }}:{{ .Values.fnserver.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
{{ toYaml .Values.fnserver.resources | indent 12 }}
          securityContext:
            privileged: true
          ports:
          - containerPort: {{ .Values.fnserver.container_port }}
          readinessProbe:
            httpGet:
              path: /v2/apps
              port: {{ .Values.fnserver.container_port }}
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
          - name: FN_DB_PASSWD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mysql
                key: mysql-password
          - name: FN_DB_HOST
            value: {{ .Release.Name }}-mysql
          - name: FN_MQ_HOST
            value: {{ .Release.Name }}-redis
          - name: FN_PORT
            value: {{ .Values.fnserver.container_port | quote }}
          - name: FN_NODE_TYPE
            value: "api"
          {{- range $key, $value := .Values.fnserver.env }}
            {{- if $value }}
          - name: {{ $key }}
            value: {{ $value | quote }}
            {{- end }}
          {{- end }}
