{{- if eq .Values.ingress.enabled true }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.fn_api.service.ingress_hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.fn_api.service.port }}
  - host: {{ .Values.fn_lb_runner.service.ingress_hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.fn_lb_runner.service.port }}
  - host: {{ .Values.ui.service.ingress_hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}-ui
          servicePort: {{ .Values.ui.service.port }}
  - host: {{ .Values.flow.service.ingress_hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}-flow
          servicePort: {{ .Values.flow.service.port }}

  {{- if eq .Values.tls.enabled true }}
  tls:
    - secretName: {{ .Values.tls.secret_reference }}
      hosts:
        - {{ .Values.fn_api.service.ingress_hostname }}
        - {{ .Values.fn_lb_runner.service.ingress_hostname }}
  {{- end -}}
{{- end -}}
