apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-lb
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
       labels:
         app: {{ template "fullname" . }}
         chart: {{ .Chart.Name }}-{{ .Chart.Version }}
         heritage: {{ .Release.Service }}
         release: {{ .Release.Name }}
         role: fn-runner
    spec:
      {{- if .Values.fn_lb_runner.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.fn_lb_runner.nodeSelector | indent 8 }}
{{- end }}
      {{- if .Values.fn_lb_runner.tolerations }}
      tolerations:
{{ toYaml .Values.fn_lb_runner.tolerations | indent 8 }}
{{- end }}
      containers:
        - name: fn-lb
          image: {{ .Values.fn_lb_runner.image }}:{{ .Values.fn_lb_runner.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
{{ toYaml .Values.fn_lb_runner.resources | indent 12 }}
          securityContext:
            privileged: true
          ports:
          - containerPort: {{ .Values.fn_lb_runner.container_port }}
          env:
          - name: FN_NODE_TYPE
            value: "lb"
          - name: FN_GRPC_PORT
            value: {{ .Values.fn_lb_runner.grpc_port | quote }}
          - name: FN_PORT
            value: {{ .Values.fn_lb_runner.container_port | quote }}
          - name: FN_RUNNER_API_URL
            value: http://{{ template "fullname" . }}-api:{{ .Values.fn_api.service.port}}
          - name: FN_RUNNER_ADDRESSES
            value: {{ template "fullname" . }}-runner.{{$.Release.Namespace}}.svc.cluster.local:{{ .Values.fn_lb_runner.service.port }}
          {{- range $key, $value := .Values.fn_lb_runner.env }}
            {{- if $value }}
          - name: {{ $key }}
            value: {{ $value | quote }}
            {{- end }}
          {{- end }}
