{{- if .Values.ui.enabled }}

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-ui
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
       labels:
         app: {{ template "fullname" . }}
         chart: {{ .Chart.Name }}-{{ .Chart.Version }}
         heritage: {{ .Release.Service }}
         release: {{ .Release.Name }}
         role: ui
    spec:
      containers:
        - name: fn-ui
          image: {{ .Values.ui.fnui.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
{{ toYaml .Values.ui.fnui.resources | indent 12 }}
          ports:
            - containerPort: 4000
          env:
          - name: PORT
            value: "80"
          - name: FN_API_URL
            value: http://{{ template "fullname" . }}-api
        - name: flow-ui
          image: {{ .Values.ui.flowui.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
{{ toYaml .Values.ui.flowui.resources | indent 12 }}
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: http://{{ template "fullname" . }}-api
            - name: COMPLETER_BASE_URL
              value: http://{{ template "fullname" . }}-flow

{{- end}} # if .Values.ui.enabled
